import 'dart:ui';

import 'package:flutter/material.dart';

const KProductCollection = 'products';
const KProductName = 'name';
const KProductPrice = 'price';
const KProductDescription = 'description';
const KProductImageUrl = 'imageUrl';
const KProductImages = 'images';
const KProductDiscount = 'discount';
const KOrders = 'orders';
const KOrderDeliveryAddress = 'deliveryAddress';
const KOrderState = 'state';
const KOrderStateActive = 'Active';
const KOrderStateFinished = 'Finished';
const KOrderStateCancelled = 'Cancelled';
const KAddress = 'address';
const KPhone = 'phone';
const KTotalPrice = 'total_price';
const KItems = 'items';
const KProductQuantity = 'quantity';
const double KBorderRadius = 4;
const double KBorderRadiusPages = 8;
const KUsers = 'users';
const KUserEmail = 'email';
const KUserName = 'name';
const KUserPhone = 'phone';
const KUserAddress = 'address';
const KUserLoggedIn = 'logged';
const KOrderAdditional = 'additional';
const Color KGreyText = Colors.grey;
